# given as a template, adapt to suit your needs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mariadb-testdbcon
  name: mariadb-testdbcon
  namespace: ${NS}
spec:
  paused: true
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-testdbcon
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb-testdbcon
    spec:
      containers:
      - env:
        - name: MYSQL_HOST
          value: "${MYSQL_HOST}"
        - name: MYSQL_PORT
          value: "${MYSQL_PORT}"
        - name: MYSQL_DBNAME
          value: "${MYSQL_DBNAME}"
        - name: MYSQL_TEST_TBL
          value: "${MYSQL_TEST_TBL}"                   
        - name: MYSQL_PASSWORD
          value: "${MYSQL_PASSWORD}"
        - name: MYSQL_USER
          value: "${MYSQL_USER}"
        image: ${TESTDBCON_IMAGE}
        imagePullPolicy: Always
        name: container
        resources:
          requests:
            cpu: 125m
            memory: 100Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: 
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
      terminationGracePeriodSeconds: 30
